name: Event Details
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  name: Output Event Details
  runs-on: ubuntu-latest
  steps:
    - name: Display github context
      run: echo ${{ github }}